version: '3'
services:
  nginx:
    image: $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - archive:/usr/share/nginx/html/archive
volumes:
  archive:
      
